"""Determinism tests at moderate scale (Step 9d, 9e, 9f).

These are the load-bearing reproducibility checks for the priors
framework:

* 9d — ``priors=None`` produces bit-for-bit identical output across two
  runs with the same seed. Distinguishes "framework is correct,
  biobank-scale seeding is fp-noisy" from "framework introduced a real
  bug." Without this, every subsequent experimental result is
  unreadable.

* 9e — ``priors=None`` matches a frozen baseline saved at
  ``tests/data/baseline_no_priors.npz``. Catches accidental behavior
  changes to the priors=None path. The baseline is regenerated by
  running ``python -m tests.gen_baseline_no_priors`` (instructions in
  the test message when the file is missing).

* 9f — ``priors=set`` produces bit-for-bit identical output across two
  runs with the same seed and the same priors config. Distinguishes
  identity-machinery bugs from harmless fp-drift.

The "10k" in the file name is aspirational — pytest scale uses 1500
haps × 500 sites × 4 ancestries × 3 EM iterations to keep CI runs
fast. The bit-for-bit invariant is independent of cohort size; the
biobank-scale validation belongs to the full AoU run.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from popout.em import run_em
from popout.simulate import simulate_admixed
from tests.conftest import make_priors_uniform


_BASELINE = Path(__file__).parent / "data" / "baseline_no_priors.npz"


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def _build_chrom():
    """Synthetic cohort used by all four tests."""
    chrom_data, _, _ = simulate_admixed(
        n_samples=750,                 # H = 1500 haps
        n_sites=500,
        n_ancestries=4,
        gen_since_admix=10,
        chrom_length_cm=80.0,
        rng_seed=4242,
    )
    return chrom_data


def _run(chrom, *, priors=None):
    return run_em(
        chrom,
        n_ancestries=4,
        n_em_iter=3,
        gen_since_admix=10.0,
        rng_seed=0,
        priors=priors,
    )


def _model_arrays(model):
    """Reduce a fitted model to the bit-for-bit-comparable arrays."""
    out = {
        "mu": np.array(model.mu, copy=True),
        "allele_freq": np.array(model.allele_freq, copy=True),
        "gen_since_admix": np.array(
            float(model.gen_since_admix), dtype=np.float64,
        ),
    }
    if model.gen_per_comp is not None:
        out["gen_per_comp"] = np.array(model.gen_per_comp, copy=True)
    return out


def _assert_models_bit_equal(a, b, label=""):
    keys = sorted(set(a) | set(b))
    for k in keys:
        assert k in a and k in b, f"{label}: missing key {k}"
        np.testing.assert_array_equal(a[k], b[k], err_msg=f"{label}: {k}")


# --------------------------------------------------------------------------
# 9d — priors=None determinism baseline
# --------------------------------------------------------------------------


def test_priors_none_bit_for_bit_reproducible():
    """Two runs of the priors=None codepath must produce bit-identical
    fitted models on the same synthetic data with the same seed.

    Failure here means there is a non-floating-point non-determinism
    source in the EM loop (or a fp non-associativity that is reaching
    the model through the priors=None path) that must be fixed before
    any priors experiment is trusted.
    """
    chrom = _build_chrom()
    a = _model_arrays(_run(chrom, priors=None).model)
    b = _model_arrays(_run(chrom, priors=None).model)
    _assert_models_bit_equal(a, b, label="priors=None")
    assert "gen_per_comp" not in a


# --------------------------------------------------------------------------
# 9e — frozen baseline
# --------------------------------------------------------------------------


@pytest.mark.skipif(
    not _BASELINE.exists(),
    reason=(
        f"frozen baseline not present at {_BASELINE}; "
        f"run `python -m tests.gen_baseline_no_priors` from the worktree "
        f"to regenerate, then re-run pytest"
    ),
)
def test_priors_none_matches_frozen_baseline():
    """The priors=None codepath must match the checked-in frozen
    baseline bit-for-bit. Regression guard against accidental behavior
    changes to the no-priors path."""
    chrom = _build_chrom()
    res = _run(chrom, priors=None)
    actual = _model_arrays(res.model)

    with np.load(_BASELINE) as f:
        baseline = {k: f[k] for k in f.files}

    _assert_models_bit_equal(actual, baseline, label="frozen baseline")


# --------------------------------------------------------------------------
# 9f — priors=set determinism
# --------------------------------------------------------------------------


def test_priors_set_bit_for_bit_reproducible():
    """Two runs of the priors codepath with identical seed and identical
    priors object must produce bit-identical models.

    Failure here means the new identity machinery introduced
    non-determinism not present in the priors=None path. Distinguishes
    framework bugs from harmless biobank-scale fp drift.
    """
    chrom = _build_chrom()
    priors = make_priors_uniform([(7, 4, 12), (2, 1, 4), (15, 8, 25)])

    a = _model_arrays(_run(chrom, priors=priors).model)
    b = _model_arrays(_run(chrom, priors=priors).model)
    _assert_models_bit_equal(a, b, label="priors=set")
    # gen_per_comp must be present on the fitted model.
    assert "gen_per_comp" in a
