version 1.0

## Split a bgzipped VCF/BCF into per-group sub-VCFs using `bcftools +split`.
## Designed for biobank-scale joint VCFs (e.g. AoU chromosome shards).
##
## Each input "sample group" file lists sample IDs (one per line). The
## file's basename (extension stripped) becomes the group name, which
## drives the output filename: <out_dir>/<group_name>.vcf.gz (+ .tbi).
##
## A single `bcftools +split` invocation produces every subset VCF in one
## streaming pass over the input — far cheaper than scattering N
## independent `bcftools view -S` jobs, each of which would re-read the
## entire input and re-pay localization cost.
##
## Resources auto-scale with input size. Defaults assume a roughly disjoint
## set of sample groups (sum of outputs ~= input size); override
## disk_size_gb_override if your groups overlap heavily.
##
## Observability: magicwand (https://github.com/broadinstitute/magicwand)
## is wired in for live W&B tracking — per-command resource attribution
## plus split-specific Tier-1 metrics. Provide `api_key` for an online run
## with a clickable URL; without it, magicwand runs W&B in offline mode.
## The W&B project is the WDL name (bcftools_split); the run name is
## auto-generated by magicwand.

task bcftools_split_task {
  input {
    File         vcf
    Array[File]  sample_groups

    # Output behavior
    String       output_type        = "z"     # z = bgzipped VCF, b = BCF
    Boolean      write_indices      = true    # tabix-index each output

    # Resource overrides (auto-scaled by VCF size by default)
    Int?         cpu_override
    String?      memory_override
    Int?         disk_size_gb_override
    String       disk_type          = "HDD"   # HDD (cheap, plenty fast for streaming), SSD, LOCAL_SSD
    Int          preemptible        = 0       # >0 = run preemptible w/ N attempts

    # Observability (magicwand -> W&B). Optional API key for online tracking.
    String?      api_key

    String       docker_image       = "us-docker.pkg.dev/broad-dsde-methods/popout/bcftools:latest"
  }

  Float vcf_gb = size(vcf, "GB")

  # Auto-scale on input VCF size. bcftools +split's cost is dominated by
  # bgzip (de)compression across all output streams, which scales with
  # --threads. Memory needs are modest because bcftools streams.
  #
  #   < 50 GB:      8 CPU,  16 GB
  #   50-150 GB:   16 CPU,  32 GB   (most AoU per-chrom shards)
  #   150-300 GB:  32 CPU,  64 GB   (chr1, chr2)
  #   > 300 GB:    64 CPU, 128 GB
  Int auto_cpu = if vcf_gb > 300.0 then 64
                 else if vcf_gb > 150.0 then 32
                 else if vcf_gb > 50.0 then 16
                 else 8
  String auto_memory = if vcf_gb > 300.0 then "128 GB"
                       else if vcf_gb > 150.0 then "64 GB"
                       else if vcf_gb > 50.0 then "32 GB"
                       else "16 GB"

  # Disk: input + sum(outputs) + headroom. For disjoint groups sum(outputs) ~ input,
  # so 2.5x leaves room for slight overlap and the tbi/csi indices.
  Int auto_disk = ceil(vcf_gb * 2.5) + 50

  Int    cpu          = select_first([cpu_override, auto_cpu])
  String memory       = select_first([memory_override, auto_memory])
  Int    disk_size_gb = select_first([disk_size_gb_override, auto_disk])

  command <<<
    set -euo pipefail

    # ---- magicwand bootstrap ----------------------------------------
    # Stub magicwand as a no-op so that a failed install.sh fetch does not
    # break the task — install.sh redefines the function on success.
    magicwand() { :; }

    ~{"export WANDB_API_KEY=" + api_key}
    export WANDB_PROJECT=bcftools_split
    source <(curl -fsSL https://raw.githubusercontent.com/broadinstitute/magicwand/main/install.sh)
    magicwand init
    # -----------------------------------------------------------------

    OUT_DIR=out
    mkdir -p "$OUT_DIR"

    # Build a single sample->group mapping for `bcftools +split -G`.
    # Group name = input file basename, last extension stripped.
    # Blank lines and `#` comments in each group file are ignored.
    : > groups.tsv
    for f in ~{sep=' ' sample_groups}; do
      group=$(basename "$f")
      group="${group%.*}"
      awk -v g="$group" 'NF && $1 !~ /^#/ { print $1 "\t" g }' "$f" >> groups.tsv
    done

    NUM_GROUPS=~{length(sample_groups)}
    NUM_MAPPINGS=$(wc -l < groups.tsv)
    echo "groups.tsv: $NUM_MAPPINGS sample/group rows across $NUM_GROUPS groups"

    magicwand log \
      bcftools_split.input_vcf_bytes="$(stat -c %s ~{vcf})" \
      bcftools_split.num_groups="$NUM_GROUPS" \
      bcftools_split.num_sample_mappings="$NUM_MAPPINGS" \
      bcftools_split.cpu="~{cpu}" \
      bcftools_split.disk_gb="~{disk_size_gb}" \
      bcftools_split.disk_type="~{disk_type}"

    bcftools +split \
      ~{vcf} \
      --groups-file groups.tsv \
      --output-type ~{output_type} \
      --output "$OUT_DIR" \
      --threads ~{cpu}

    ls -lh "$OUT_DIR"

    # Tier-1 post-split metrics: how many outputs landed, and total size.
    OUTPUT_COUNT=$(find "$OUT_DIR" -maxdepth 1 -type f \( -name '*.vcf.gz' -o -name '*.bcf' \) | wc -l)
    TOTAL_OUTPUT_BYTES=$(du -bcs "$OUT_DIR" | tail -1 | awk '{print $1}')
    magicwand log \
      bcftools_split.output_count="$OUTPUT_COUNT" \
      bcftools_split.total_output_bytes="$TOTAL_OUTPUT_BYTES"

    if [ "~{write_indices}" = "true" ]; then
      for f in "$OUT_DIR"/*.vcf.gz; do
        [ -e "$f" ] || continue
        bcftools index --tbi --threads ~{cpu} "$f"
      done
      for f in "$OUT_DIR"/*.bcf; do
        [ -e "$f" ] || continue
        bcftools index --threads ~{cpu} "$f"
      done
    fi
  >>>

  output {
    Array[File] subset_vcfs    = flatten([glob("out/*.vcf.gz"), glob("out/*.bcf")])
    Array[File] subset_indices = flatten([glob("out/*.tbi"),    glob("out/*.csi")])
  }

  runtime {
    docker:      docker_image
    cpu:         cpu
    memory:      memory
    disks:       "local-disk ~{disk_size_gb} ~{disk_type}"
    preemptible: preemptible
  }
}

workflow bcftools_split {
  input {
    File         vcf
    Array[File]  sample_groups

    String       output_type           = "z"
    Boolean      write_indices         = true

    Int?         cpu_override
    String?      memory_override
    Int?         disk_size_gb_override
    String       disk_type             = "HDD"
    Int          preemptible           = 0

    String?      api_key

    String       docker_image          = "us-docker.pkg.dev/broad-dsde-methods/popout/bcftools:latest"
  }

  call bcftools_split_task {
    input:
      vcf                    = vcf,
      sample_groups          = sample_groups,
      output_type            = output_type,
      write_indices          = write_indices,
      cpu_override           = cpu_override,
      memory_override        = memory_override,
      disk_size_gb_override  = disk_size_gb_override,
      disk_type              = disk_type,
      preemptible            = preemptible,
      api_key                = api_key,
      docker_image           = docker_image
  }

  output {
    Array[File] subset_vcfs    = bcftools_split_task.subset_vcfs
    Array[File] subset_indices = bcftools_split_task.subset_indices
  }
}
